import type { Metadata } from "next";
import { Bebas_Neue, Inter, Outfit } from "next/font/google";
import "../styles/globals.css";

import LayoutWrapper from "@/components/templates/LayoutWrapper";
import { cn } from "@/lib/utils";

const bebas_neue = Bebas_Neue({
  subsets: ["latin"],
  weight: "400",
  preload: true,
  variable: "--font-bebas-neue",
});

const outfit = Outfit({
  subsets: ["latin"],
  display: "swap",
  weight: ["300", "400", "500", "700"],
  preload: true,
  variable: "--font-outfit",
});

const inter = Inter({ subsets: ["latin"], preload: true });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "flex w-full flex-col items-center bg-[#EFF1F8] mb-12",
          bebas_neue.variable,
          outfit.variable,
          inter.className,
        )}
      >
        <LayoutWrapper>{children}</LayoutWrapper>
      </body>
    </html>
  );
}
