import type { Metadata } from "next";
import { Bebas_Neue, Inter, Outfit } from "next/font/google";
import "../styles/globals.css";
import MainNav from "@/components/organisms/MainNav";

const bebas_neue = Bebas_Neue({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-bebas-neue",
});

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-outfit",
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`flex justify-center bg-[#EFF1F8] ${bebas_neue.variable} ${outfit.variable} ${inter.className}`}
      >
        <MainNav />
        {children}
      </body>
    </html>
  );
}
